version: "3.9"

services:
  db:
    image: postgres:15
    container_name: app_db
    environment:
      - POSTGRES_USER=new
      - POSTGRES_PASSWORD=new
      - POSTGRES_DB=new
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    image: ssmagon/django_app:latest
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - PG_USER=new
      - PG_PASSWORD=new
      - PG_DB=new
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db

volumes:
  pgdata:
