# Generated by Django 3.2.22 on 2024-05-06 10:57

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentationCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentation_camera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carburants_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('quantite', models.CharField(max_length=255)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_approvisionnement', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieEngrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_engrais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieGrainesPousses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_graines_pousses', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_traitement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ColorReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('color_css', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filtre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('descriptionFr', models.TextField()),
                ('descriptionAr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Frigo_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hangar_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogistiquesPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_logistiques', 'Can view logistiques')],
            },
        ),
        migrations.CreateModel(
            name='Machines_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=255)),
                ('marque', models.CharField(max_length=255)),
                ('carte_grise', models.CharField(max_length=255)),
                ('date_assurance', models.CharField(max_length=100)),
                ('date_visite', models.CharField(max_length=100)),
                ('date_vignette', models.CharField(max_length=100)),
                ('allocation', models.CharField(max_length=3)),
                ('prix_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_location', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_achat', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maison_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarqueControleAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque_controle_acces', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarqueDvrNvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque_dvr_nvr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NbrChaineDvrNvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_chaine_dvr_nvr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Outils_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('numero_de_serie', models.CharField(max_length=255)),
                ('marque', models.CharField(max_length=255)),
                ('allocation', models.CharField(max_length=3)),
                ('prix_location_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_location_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_location_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_location', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_achat', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pieces_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_achat', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_projects', 'Can view projects')],
            },
        ),
        migrations.CreateModel(
            name='SectionVanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_vanne', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAntiIncendie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anti_incendie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_carburant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCarburantGenerateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_carburant_generateur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompteurPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compteur_poste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeControleAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_controle_acces', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCouplageMoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_couplage_moteur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDetectionIntrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_detection_intrusion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEngrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_engrais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeGrainesPousses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_graines_pousses', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeHangerDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hanger_depot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMachineEngins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_machine_engins', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaisonVilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_Maison_Villa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_moteur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOutilsAgricoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_outils_agricoles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pieces', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pivot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_puit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePulverisateuraxiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pulverisateur_axiale', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeReservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reservoir', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSvsCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_svs_camera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTensionGenerateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tension_generateur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTensionMoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tension_moteur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_traitement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vanne', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('circle_radius', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('circle_radius', models.CharField(max_length=100)),
                ('id_projet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Traitement_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=255)),
                ('composition', models.CharField(max_length=50)),
                ('mode_utilisation', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_achat', models.CharField(blank=True, max_length=100, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('description', models.TextField(null=True)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Rh_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('num_tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('fonction', models.CharField(max_length=100)),
                ('salaire_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('matricule_cnss', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('date_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=255)),
                ('activity', models.CharField(blank=True, max_length=255)),
                ('matricule', models.CharField(blank=True, max_length=20)),
                ('address_company', models.TextField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('website_company', models.URLField(blank=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('type_of_agriculture', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latt', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zoneparcelle')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latt', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='MapFormParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle_name', models.CharField(max_length=100)),
                ('parcelle_date', models.CharField(max_length=100)),
                ('parcelle_category', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('id_projet', models.TextField()),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zoneparcelle')),
            ],
        ),
        migrations.CreateModel(
            name='MapForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_date', models.CharField(max_length=100)),
                ('project_category', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graine_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=255)),
                ('origine', models.CharField(max_length=50)),
                ('quantite', models.CharField(max_length=100)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('description', models.TextField(null=True)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Engrais_Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=255)),
                ('composition', models.CharField(max_length=50)),
                ('mode_utilisation', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_achat', models.CharField(blank=True, max_length=100, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('description', models.TextField(null=True)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
    ]
