# Generated by Django 3.2.22 on 2024-05-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapform',
            name='user',
        ),
    ]
