# Generated by Django 3.2.22 on 2024-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_mapform_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorReferenceNdmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('color_css', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
