# Generated by Django 3.2.22 on 2024-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_new_oper_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='disease_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
