# Generated by Django 3.2.22 on 2024-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_anomaly_symptomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltreEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('descriptionFr', models.TextField()),
                ('descriptionAr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FiltreFertilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('descriptionFr', models.TextField()),
                ('descriptionAr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FiltreHumidite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('descriptionFr', models.TextField()),
                ('descriptionAr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FiltreIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('descriptionFr', models.TextField()),
                ('descriptionAr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FiltreMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('descriptionFr', models.TextField()),
                ('descriptionAr', models.TextField()),
            ],
        ),
    ]
