# Generated by Django 3.2.22 on 2024-07-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_filtre_filtrevegitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('descriptionFr', models.TextField()),
                ('descriptionAr', models.TextField()),
            ],
        ),
    ]
