# Generated by Django 3.2.22 on 2024-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_filtre'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtreevolution',
            name='details',
            field=models.CharField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='filtrefertilisation',
            name='details',
            field=models.CharField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='filtrehumidite',
            name='details',
            field=models.CharField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='filtreirrigation',
            name='details',
            field=models.CharField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='filtremaladie',
            name='details',
            field=models.CharField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='filtrevegitation',
            name='details',
            field=models.CharField(default='default_value', max_length=500),
        ),
    ]
