# Generated by Django 3.2.22 on 2024-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240730_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtreevolution',
            name='details',
            field=models.CharField(default='default_value', max_length=5000),
        ),
        migrations.AlterField(
            model_name='filtrefertilisation',
            name='details',
            field=models.CharField(default='default_value', max_length=5000),
        ),
        migrations.AlterField(
            model_name='filtrehumidite',
            name='details',
            field=models.CharField(default='default_value', max_length=5000),
        ),
        migrations.AlterField(
            model_name='filtreirrigation',
            name='details',
            field=models.CharField(default='default_value', max_length=5000),
        ),
        migrations.AlterField(
            model_name='filtremaladie',
            name='details',
            field=models.CharField(default='default_value', max_length=5000),
        ),
        migrations.AlterField(
            model_name='filtrevegitation',
            name='details',
            field=models.CharField(default='default_value', max_length=5000),
        ),
    ]
