# Generated by Django 3.2.22 on 2024-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorreference',
            name='filter_name',
            field=models.CharField(default='NDRE', max_length=50),
        ),
        migrations.AddField(
            model_name='colorreferencemsavi',
            name='filter_name',
            field=models.CharField(default='MSAVI 2', max_length=50),
        ),
        migrations.AddField(
            model_name='colorreferencendmi',
            name='filter_name',
            field=models.CharField(default='NDMI', max_length=50),
        ),
    ]
