# Generated by Django 3.2.22 on 2024-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20240801_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorreferencemsavi',
            name='filter_name',
            field=models.CharField(default='MSAVI2', max_length=50),
        ),
    ]
