# Generated by Django 3.2.22 on 2024-08-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_colorreferencemsavi_filter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorReferenceNdvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(default='NDVI', max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('color_css', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
