# Generated by Django 3.2.22 on 2024-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_colorreferencendvi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionFiltre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
