# Generated by Django 3.2.22 on 2024-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20240815_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_oper_tables',
            old_name='duree_utilisation',
            new_name='heure_de_fin',
        ),
        migrations.RenameField(
            model_name='new_oper_tables',
            old_name='duree_utilisation_piece',
            new_name='nombre_de_pieces',
        ),
        migrations.AddField(
            model_name='new_oper_tables',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='new_oper_tables',
            name='timefin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
