# Generated by Django 3.2.22 on 2024-08-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20240828_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='outil',
        ),
        migrations.AddField(
            model_name='new_oper_tables',
            name='outil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
