# Generated by Django 3.2.22 on 2024-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20240903_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDoeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rh', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('timefin', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='time',
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='timefin',
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='type_rh',
        ),
        migrations.AddField(
            model_name='new_oper_tables',
            name='main_doeuvres',
            field=models.ManyToManyField(related_name='operations', to='app.MainDoeuvre'),
        ),
    ]
