# Generated by Django 3.2.22 on 2024-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20240903_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_machine_engins', models.CharField(max_length=100)),
                ('carburant', models.CharField(max_length=100)),
                ('duree_utilisation_programme', models.DateTimeField()),
                ('heure_de_fin', models.DateTimeField()),
                ('quantite_carburant', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='carburant',
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='duree_utilisation_programme',
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='heure_de_fin',
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='quantite_carburant',
        ),
        migrations.RemoveField(
            model_name='new_oper_tables',
            name='type_machine_engins',
        ),
        migrations.AddField(
            model_name='new_oper_tables',
            name='machine_carburants',
            field=models.ManyToManyField(related_name='operations', to='app.MachineCarburant'),
        ),
    ]
