# Generated by Django 3.2.22 on 2024-09-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_oper_tables',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app.mapform'),
        ),
    ]
