# Generated by Django 3.2.22 on 2024-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_new_oper_tables_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoeuvre',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maindoeuvre',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maindoeuvre',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maindoeuvre',
            name='type_rh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
