# Generated by Django 3.2.22 on 2024-09-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20240905_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindoeuvre',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='maindoeuvre',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='maindoeuvre',
            name='type',
        ),
        migrations.AlterField(
            model_name='maindoeuvre',
            name='type_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rh_tables'),
        ),
    ]
