# Generated by Django 3.2.22 on 2024-09-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20240905_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecarburant',
            name='type_machine_engins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.machines_tables'),
        ),
    ]
