# Generated by Django 3.2.22 on 2024-09-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_machinecarburant_type_machine_engins'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapform',
            name='points',
            field=models.ManyToManyField(related_name='projects', to='app.Point'),
        ),
    ]
