# Generated by Django 3.2.22 on 2024-09-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_mapform_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapform',
            name='points',
        ),
    ]
