# Generated by Django 3.2.22 on 2024-09-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_new_oper_tables_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='app.new_oper_tables'),
        ),
    ]
