# Generated by Django 3.2.22 on 2024-09-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_marker_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='operation',
        ),
    ]
