# Generated by Django 3.2.22 on 2024-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_marker_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='operation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
