# Generated by Django 3.2.22 on 2024-09-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_marker_operation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='operation_id',
        ),
    ]
