# Generated by Django 3.2.22 on 2024-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_marker_operation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_oper_tables',
            name='markers',
            field=models.ManyToManyField(blank=True, null=True, related_name='operations', to='app.Marker'),
        ),
    ]
