# Generated by Django 3.2.22 on 2024-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_new_oper_tables_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_oper_tables',
            name='markers',
            field=models.ManyToManyField(related_name='operations', to='app.Marker'),
        ),
    ]
