# Generated by Django 3.2.22 on 2024-09-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_new_oper_tables_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_oper_tables',
            name='date_debut',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='new_oper_tables',
            name='date_fin',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
