# Generated by Django 3.2.22 on 2024-09-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20240913_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_oper_tables',
            name='outils',
            field=models.ManyToManyField(related_name='operations', to='app.Tool'),
        ),
    ]
