# Generated by Django 3.2.22 on 2024-09-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_new_oper_tables_outils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechangepiece',
            name='type_pieces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.typepieces'),
        ),
    ]
