# Generated by Django 3.2.22 on 2024-09-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_rechangepiece_type_pieces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RechangePiece',
            new_name='RechangePiecee',
        ),
    ]
