# Generated by Django 3.2.22 on 2024-10-25 13:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_mapform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.filepath),
        ),
    ]
