# Generated by Django 3.2.22 on 2024-10-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_mapform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapform',
            name='project_date',
            field=models.DateField(),
        ),
    ]
