# Generated by Django 3.2.22 on 2024-11-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_mapform_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField()),
                ('anomaly_detected', models.BooleanField(default=False)),
            ],
        ),
    ]
