from django.contrib import admin
from .models import * 

# Register your models here.
#admin.site.register(UserProfile)
admin.site.register(LogistiquesPermission)
admin.site.register(ProjectsPermission)
admin.site.register(Hangar_Tables)

admin.site.register(Profile)
admin.site.register(ProfileCompany)

admin.site.register(Machines_Tables)
admin.site.register(Outils_Tables)
admin.site.register(Zone)
admin.site.register(Point)
admin.site.register(MapForm)
admin.site.register(ZoneParcelle)
admin.site.register(MapFormParcelle)
""" admin.site.register(Filtre) """
admin.site.register(ColorReference)
admin.site.register(Carburants_Tables)
admin.site.register(Pieces_Tables)
admin.site.register(Rh_Tables)
admin.site.register(Graine_Tables)
admin.site.register(Traitement_Tables)
admin.site.register(Engrais_Tables)
admin.site.register(Maison_Tables)
admin.site.register(TypeMachineEngins)
admin.site.register(TypeOutilsAgricoles)
admin.site.register(TypePuit)
admin.site.register(TypeReservoir)
admin.site.register(TypeVanne)
admin.site.register(SectionVanne)
admin.site.register(TypePivot)
admin.site.register(TypePulverisateuraxiale)
admin.site.register(TypeCompteurPoste)
admin.site.register(TypeTensionGenerateur)
admin.site.register(TypeCarburantGenerateur)
admin.site.register(TypeMoteur)
admin.site.register(TypeTensionMoteur)
admin.site.register(TypeCouplageMoteur)
admin.site.register(TypeSvsCamera)
admin.site.register(MarqueDvrNvr)
admin.site.register(NbrChaineDvrNvr)
admin.site.register(AlimentationCamera)
admin.site.register(TypeAntiIncendie)
admin.site.register(TypeDetectionIntrusion)
admin.site.register(TypeControleAcces)
admin.site.register(MarqueControleAcces)
admin.site.register(TypeMaisonVilla)
admin.site.register(TypeHangerDepot)
admin.site.register(TypeFrigo)
admin.site.register(TypeEngrais)
admin.site.register(CategorieEngrais)
admin.site.register(TypeTraitement)
admin.site.register(CategorieTraitement)
admin.site.register(TypeGrainesPousses)
admin.site.register(CategorieGrainesPousses)
admin.site.register(TypeCarburant)
admin.site.register(TypePieces)
admin.site.register(TypeRh)

